# Configurações gerais
title: Refinale
baseurl: "index.html" # Substitua pelo nome do seu repositório se estiver em um subdiretório
destination: docs

# Configurações do tema (se estiver usando um tema)
theme: jekyll-theme-cayman # Substitua pelo tema que você está usando
exclude:
  - assets/css/style.scss

# Configurações adicionais
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _config.yml